name: ci pipelines

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'feat/**'
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make test application_yml
        env:
          APPLICATION_YML: ${{ secrets.APPLICATION_YML }}
        run: |
          mkdir -p ./src/test/resources && cd "$_"
          touch ./application.yml
          echo $APPLICATION_YML | base64 --decode > application.yml
        shell: bash

      - name: Grant
        run : chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Notify on success
        if: success()
        run: echo "All tests passed!"
