name: ci pipelines

on:
  pull_request:
    branches:
      - dev
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run tests
        env:
          spring_profiles_active: test
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_PUBLIC: ${{ secrets.S3_PUBLIC }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_REGION: ${{ secrets.S3_REGION }}
        run: ./gradlew test -Dspring.profiles.active=test -i

      - name: Notify on success
        if: success()
        run: echo "All tests passed!"

      - name: Notify on failure
        if: failure()
        run: echo "Some tests failed!"
