name: ci pipelines

on:
  pull_request:
    branches:
      - dev
  push:
    branches: [ dev ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Run tests with H2 DB
        env:
          spring_profiles_active: test
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_PUBLIC: ${{ secrets.S3_PUBLIC }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_REGION: ${{ secrets.S3_REGION }}
          SLACKBOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
          LOGSTASH_HOST: ${{ secrets.LOGSTASH_HOST }}
          LOGSTASH_PORT: ${{ secrets.LOGSTASH_PORT }}
        run: ./gradlew test -Dspring.profiles.active=test

      - name: Register test results as comments in PR
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: If the test fails, register a Check comment in the failed code line
        uses: mikepenz/action-junit-report@v3
        if: failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

  notification:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}

    if: failure() && (needs.build.result == 'failure' || needs.test.result == 'failure')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR title
        if: env.PR_TITLE == null
        run: |
          echo "PR_TITLE=$(gh pr list --head ${{ github.ref_name }} --json title --jq '.[0].title')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: If the jobs fail, send to slack message
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "attachments": [
                    {
                      "title": "🚩 PR이 실패했습니다.",
                      "color": "danger",
                      "fields": [
                        {
                          "title": "PR 제목",
                          "value": "${{ env.PR_TITLE }}",
                          "short": true
                        },
                        {
                          "title": "PR 요청자",
                          "value": "${{ github.actor }}",
                          "short": true
                        },
                        {
                          "title": "Branch",
                          "value": "${{github.ref}}",
                          "short": true
                        },
                        {
                          "title": "Actions URL",
                          "value": "<${{github.server_url}}/${{github.repository}}/commit/${{github.sha}}/checks|${{github.workflow}}>",
                          "short": true
                        },
                        {
                          "title": "Commit Link",
                          "value": "<${{github.server_url}}/${{github.repository}}/commit/${{github.sha}}|Commit Link>",
                          "short": true
                        },
                        {
                          "title": "커밋 메시지",
                          "value": "${{github.event.head_commit.message}}",
                          "short": true
                        }
                      ]
                    }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK